server:
  # 指定Tomcat端口
  port: 21000
  servlet:
    context-path: /ironMan
spring:
  application.name: iron-man
  jpa:
    # 让hibernate打印执行的SQL
    show-sql: true
  h2:
    console:
      path: /console
      enabled: true
      settings:
        web-allow-others: true
logging:
  level:
    root: INFO
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://cat:20001/shield/eureka,http://dog:20002/shield/eureka
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'